name: Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build 
      run: GOOS=linux GOARCH=386 go build -o app-linux-386 main.go
      run: GOOS=linux GOARCH=amd64 go build -o app-linux-amd64 main.go
      run: GOOS=linux GOARCH=arm go build -o app-linux-arm main.go
      run: GOOS=linux GOARCH=arm64 go build -o app-linux-arm64 main.go
      run: GOOS=darwin GOARCH=386 go build -o app-darwin-386 main.go
      run: GOOS=darwin GOARCH=amd64 go build -o app-darwin-amd64 main.go
      run: GOOS=windows GOARCH=386 go build -o app-windows-386.exe main.go
      run: GOOS=windows GOARCH=amd64 go build -o app-windows-amd64.exe main.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release 1.0.0
        body: This is the first release.
        draft: false
        prerelease: false

    - name: Attach artifacts to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          app-linux-386
          app-linux-amd64
          app-linux-arm64
          app-darwin-386
          app-darwin-amd64
          app-windows-386.exe
          app-windows-amd64.exe
          
        asset_name: myapp
        asset_content_type: application/octet-stream
